# Generated by Django 5.2.15 on 2026-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20160701_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('simple_choice', 'Simple Choice'), ('multiple_choice', 'Multiple Choice')], default='simple_choice', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.UniqueConstraint(fields=('identifier',), name='vote_poll_identifier_unique'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('token_string',), name='vote_token_token_string_unique'),
        ),
    ]
