# Generated by Django 5.2.15 on 2026-08-04 10:56
#
# The queue of the paced mail sender (notes/plan.md §11.7).
#
# **Purely additive, unlike 0003:** a *new* table appears here, no existing one is touched. So
# SQLite has nothing to rewrite -- 0003 rewrote `vote_poll` and `vote_token`, because a constraint
# cannot be attached after the fact (notes/phase-2-migrations.md). This migration is therefore
# harmless, however much data is in the database.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_model_constraints_and_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
