# Generated by Django 5.2.15 on 2026-08-04 10:56
#
# Die Warteschlange des getakteten Mailversands (notes/plan.md §11.7).
#
# **Rein additiv, anders als 0003:** hier entsteht eine *neue* Tabelle, keine bestehende wird
# angefasst. SQLite muss dafür also nichts umschreiben -- 0003 hat `vote_poll` und `vote_token` neu
# geschrieben, weil ein Constraint nicht nachträglich anhängbar ist (notes/phase-2-migrations.md).
# Diese Migration ist damit unkritisch, egal wie viele Daten in der Datenbank liegen.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_model_constraints_and_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
